#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 13 06:31:13 HKT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Medium
enableShaders=false
