#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 16 05:52:06 HKT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Low
enableShaders=false
